<h1>Connexion</h1>
<form action="index.php?route=login" method="POST">
    <fieldset>
        <label for="login-email">Email</label>
        <input type="email" name="login-email" id="login-email"/>
    </fieldset>
    <fieldset>
        <label for="login-password">Mot de passe</label>
        <input type="password" name="login-password" id="login-password"/>
    </fieldset>
    <input type="submit" name="submit-login" id="submit-login" value="Se connecter"/>
</form>